;this file for FamiTone2 library generated by text2data tool

jesaispas_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,368,307

.instruments:
	.db $b0 ;instrument $00
	.dw .env1,.env3,.env0
	.db $00
	.db $b0 ;instrument $01
	.dw .env1,.env3,.env5
	.db $00
	.db $30 ;instrument $02
	.dw .env2,.env4,.env0
	.db $00
	.db $b0 ;instrument $03
	.dw .env1,.env0,.env5
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $c9,$ce,$cf,$cf,$cc,$c9,$c7,$c6,$c6,$c5,$c4,$c3,$c2,$c2,$00,$0d
.env2:
	.db $cf,$02,$ce,$cd,$cb,$c8,$c5,$c3,$c1,$02,$c0,$00,$0a
.env3:
	.db $c0,$c5,$c0,$c5,$c0,$c5,$00,$00
.env4:
	.db $c0,$c8,$00,$01
.env5:
	.db $e1,$ff,$04,$ff,$00,$03


.song0ch0:
	.db $fb,$04
.song0ch0loop:
.ref0:
	.db $f9,$85
.ref1:
	.db $f9,$85
.ref2:
	.db $f9,$85
.ref3:
	.db $f9,$85
.ref4:
	.db $f9,$85
.ref5:
	.db $f9,$85
.ref6:
	.db $f9,$85
.ref7:
	.db $f9,$85
.ref8:
	.db $f9,$85
.ref9:
	.db $f9,$85
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref10:
	.db $f9,$85
.ref11:
	.db $f9,$85
.ref12:
	.db $f9,$85
.ref13:
	.db $f9,$85
.ref14:
	.db $80,$24,$85,$25,$25,$24,$85,$24,$85,$28,$85,$29,$29,$28,$85,$28
	.db $85,$2c,$85,$2d,$2d,$2c,$85,$2c,$85,$2c,$85,$2d,$2d,$2c,$85,$2c
	.db $85
.ref15:
	.db $24,$85,$25,$25,$24,$85,$24,$85,$28,$85,$29,$29,$28,$85,$28,$85
	.db $1e,$85,$1f,$1f,$1e,$85,$1e,$85,$1e,$8d,$00,$8d
.ref16:
	.db $24,$85,$25,$25,$24,$85,$24,$85,$28,$85,$29,$29,$28,$85,$28,$85
	.db $2c,$85,$2d,$2d,$2c,$85,$2c,$85,$2c,$85,$2d,$2d,$2c,$85,$2c,$85
	.db $ff,$1c
	.dw .ref15
.ref18:
	.db $f9,$85
.ref19:
	.db $f9,$85
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref20:
	.db $86,$2c,$9d,$28,$9d,$24,$8d,$28,$85,$2c,$9d,$2e,$85
.ref21:
	.db $2c,$9d,$28,$9d,$24,$8d,$28,$85,$1c,$a1,$00,$81
.ref22:
	.db $2c,$9d,$28,$9d,$24,$8d,$28,$85,$2c,$9d,$2e,$85
	.db $ff,$0c
	.dw .ref21
	.db $ff,$0c
	.dw .ref22
	.db $ff,$0c
	.dw .ref21
	.db $ff,$0c
	.dw .ref22
	.db $ff,$0c
	.dw .ref21
	.db $ff,$0c
	.dw .ref22
	.db $ff,$0c
	.dw .ref21
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref30:
	.db $f9,$85
.ref31:
	.db $f9,$85
.ref32:
	.db $86,$06,$8d,$1a,$85,$1b,$84,$1f,$86,$06,$8d,$1a,$85,$1b,$84,$1f
	.db $86,$06,$8d,$1a,$85,$1b,$84,$1f,$86,$06,$8d,$1a,$85,$1b,$84,$1e
	.db $81
	.db $ff,$19
	.dw .ref32
	.db $ff,$19
	.dw .ref32
	.db $ff,$19
	.dw .ref32
	.db $ff,$19
	.dw .ref32
	.db $ff,$19
	.dw .ref32
	.db $ff,$19
	.dw .ref32
	.db $ff,$19
	.dw .ref32
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref40:
	.db $f9,$85
.ref41:
	.db $f9,$85
.ref42:
	.db $f9,$85
.ref43:
	.db $f9,$85
.ref44:
	.db $f9,$85
.ref45:
	.db $f9,$85
.ref46:
	.db $f9,$85
.ref47:
	.db $f9,$85
.ref48:
	.db $f9,$85
.ref49:
	.db $f9,$85
	.db $fd
	.dw .song0ch4loop
